# Generated by Django 5.0.4 on 2025-11-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_create_task', 'Can Create Task')]},
        ),
    ]
